### ISSUE TITLE
training batch setting with 1080Ti

### ISSUE THREAD

**Issue by cvtower** [1e100/mnasnet_trainer#2]
Dear @1e100 ,

Nice work!
According to my experience, training mnasnet will takes about 7~8G GPU memory for batch_size=96(mobilenetV2 setting), since i tried to reproduce paper values with pytorch 0.4 months ago.
Are you sure that you could use batch_size=740 for mnasnet1.0 with only 4 1080Ti?
Would you please share batch size setting to reproduce paper value? since it is never mentioned and part of the training paras were changed compare to paper v1.

Thanks very much for your help!

**Comment by 1e100** [comment]
Yes, that's how I train it. Note that the meaning of "batch" sometimes differs between the various training code implementations. In some cases people mean "batch per gpu". Here it means "overall batch size", so batch per GPU is 185. This batch size maximizes the GPU utilization with my code.

**Comment by 1e100** [comment]
BTW, if you know good settings for 0.75 and 1.3, do share. I haven't yet been able to reach close-to-paper numbers on those two configurations. I focused on 1.0 and 0.5.
